# Site Settings
title: WT's Life Blog
SEOTitle: 歪婷的博客 | WT's Blog
email: chingwaiteng@outlook.com
description: "No Try No Life."
url: "https://cwteng1005.github.io/WT_Blog/"
header-img: img/flower.jpg

# Sidebar Settings
sidebar: true
sidebar-about-description: "I can do all things through CHRIST who strengthens me. \n【Philippians 4:13】"
sidebar-avatar: img/墨镜猫头像.jpg

# SNS Settings
RSS: false
github_username: CWTeng1005

# Build Settings
permalink: pretty
paginate: 7
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Gems
gems: [jekyll-paginate]

# Markdown Settings
markdown: kramdown
highlighter: rouge
kramdown:
input: GFM

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
